import { useState } from "react";
import { X, FileText, ShieldCheck, Download } from "lucide-react";
import { StatusChip } from "@/components/shared/StatusChip";

interface PayoutBatch {
  id: string;
  batch: string;
  date: string;
  nurses: number;
  gross: string;
  commission: string;
  net: string;
}

interface ApprovePayoutModalProps {
  batch: PayoutBatch;
  onCancel: () => void;
  onApprove: () => void;
}

/** Generates a plain-text "PDF" summary and triggers a browser download. */
function downloadPayoutSummary(batch: PayoutBatch) {
  const lines = [
    "NURSECONNECT â€” PAYOUT SUMMARY",
    "=".repeat(40),
    "",
    `Batch ID      : ${batch.id}`,
    `Batch Name    : ${batch.batch}`,
    `Date          : ${batch.date}`,
    `Nurses        : ${batch.nurses}`,
    "",
    `Gross Amount  : ${batch.gross}`,
    `Commission    : ${batch.commission}`,
    `Net Payout    : ${batch.net}`,
    "",
    "=".repeat(40),
    `Generated at  : ${new Date().toLocaleString("en-IN")}`,
    "",
    "This document is auto-generated by NurseConnect Finance.",
  ].join("\n");

  const blob = new Blob([lines], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `Payout_Summary_${batch.id}.pdf`;
  a.click();
  URL.revokeObjectURL(url);
}

export function ApprovePayoutModal({ batch, onCancel, onApprove }: ApprovePayoutModalProps) {
  const [verified, setVerified] = useState(false);

  return (
    /* Backdrop */
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm">
      {/* Modal card */}
      <div className="relative w-full max-w-lg mx-4 bg-white rounded-2xl shadow-2xl border border-border overflow-hidden">

        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-border">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center">
              <ShieldCheck className="w-4 h-4 text-primary" />
            </div>
            <h2 className="text-[15px] font-semibold text-foreground">Approve Payout Batch</h2>
          </div>
          <button
            onClick={onCancel}
            className="w-7 h-7 rounded-md flex items-center justify-center hover:bg-muted/60 transition-colors"
          >
            <X className="w-4 h-4 text-muted-foreground" />
          </button>
        </div>

        {/* Body */}
        <div className="px-6 py-5 space-y-5">

          {/* Batch detail grid */}
          <div className="grid grid-cols-2 gap-x-6 gap-y-3.5 text-[13px]">
            <DetailRow label="Batch ID" value={<span className="font-mono text-[12px]">{batch.id}</span>} />
            <DetailRow label="Batch Name" value={batch.batch} />
            <DetailRow label="Date" value={batch.date} />
            <DetailRow label="Nurses" value={String(batch.nurses)} />
            <DetailRow label="Gross Amount" value={batch.gross} />
            <DetailRow label="Commission" value={batch.commission} />
            <div className="col-span-2">
              <DetailRow
                label="Net Payout"
                value={
                  <span className="text-[14px] font-bold text-foreground">{batch.net}</span>
                }
              />
            </div>
          </div>

          {/* Divider */}
          <div className="border-t border-border" />

          {/* Supporting document */}
          <div>
            <p className="text-[12px] font-medium text-muted-foreground mb-2 uppercase tracking-wide">
              Supporting Document
            </p>
            <button
              type="button"
              onClick={() => downloadPayoutSummary(batch)}
              className="flex items-center gap-3 px-3.5 py-2.5 rounded-lg bg-muted/40 border border-border hover:bg-primary/5 hover:border-primary/30 transition-colors cursor-pointer w-fit group"
            >
              <div className="w-7 h-7 rounded bg-primary/10 flex items-center justify-center flex-shrink-0">
                <FileText className="w-3.5 h-3.5 text-primary" />
              </div>
              <span className="text-[13px] font-medium text-foreground">
                Payout_Summary_{batch.id}.pdf
              </span>
              <StatusChip tone="info" label="PDF" />
              <Download className="w-3.5 h-3.5 text-muted-foreground group-hover:text-primary transition-colors ml-1" />
            </button>
            <p className="text-[11px] text-muted-foreground mt-1.5 ml-0.5">
              Click to download the payout summary document
            </p>
          </div>

          {/* Verification checkbox */}
          <label className="flex items-start gap-3 cursor-pointer group">
            <div className="relative mt-0.5 flex-shrink-0">
              <input
                type="checkbox"
                className="sr-only"
                checked={verified}
                onChange={e => setVerified(e.target.checked)}
              />
              <div
                className={`w-4.5 h-4.5 w-[18px] h-[18px] rounded border-2 transition-all flex items-center justify-center ${
                  verified
                    ? "bg-primary border-primary"
                    : "border-muted-foreground/40 group-hover:border-primary/60"
                }`}
              >
                {verified && (
                  <svg viewBox="0 0 10 8" className="w-2.5 h-2.5 fill-none stroke-white stroke-2">
                    <path d="M1 4l3 3 5-6" strokeLinecap="round" strokeLinejoin="round" />
                  </svg>
                )}
              </div>
            </div>
            <span className="text-[13px] text-muted-foreground leading-relaxed">
              I have verified the above details and confirm this batch is ready for payout.
            </span>
          </label>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-end gap-3 px-6 py-4 border-t border-border bg-muted/20">
          <button
            onClick={onCancel}
            className="px-4 py-2 text-[13px] font-medium rounded-lg border border-border bg-white hover:bg-muted/40 transition-colors text-foreground"
          >
            Cancel
          </button>
          <button
            onClick={onApprove}
            disabled={!verified}
            className={`px-4 py-2 text-[13px] font-medium rounded-lg transition-colors text-white ${
              verified
                ? "bg-primary hover:bg-primary/90 cursor-pointer"
                : "bg-primary/40 cursor-not-allowed"
            }`}
          >
            Approve Batch
          </button>
        </div>
      </div>
    </div>
  );
}

function DetailRow({ label, value }: { label: string; value: React.ReactNode }) {
  return (
    <div>
      <p className="text-[11px] font-medium text-muted-foreground uppercase tracking-wide mb-0.5">{label}</p>
      <div className="text-[13px] font-medium text-foreground">{value}</div>
    </div>
  );
}
